name: Check code quality

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.9.13
      - name: Run formatters
        run: black --check ./ && isort --check-only ./
      - name: Run linter
        run: flake8 ./
